/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primitivas_graficas;

import Modelos.Circulo;
import Modelos.Cuadrado;
import Modelos.Imagen;
import Modelos.Rectangulo;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;

/**
 *
 * @author valen
 */
public class Inicio extends javax.swing.JFrame {
        Imagen player;
        Thread proceso;
        Lienzo lienzo1;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
         this.lienzo1=new Lienzo();
        
        this.lienzo1.setVisible(true);
        this.lienzo1.setSize(585, 650);
        this.lienzo1.setBackground(Color.black);
        Point p=new Point(70, 10);
        this.lienzo1.setLocation(p);
        this.add(lienzo1);
        this.setLocationRelativeTo(null);
        this.setTitle("GALAXY GAME");
        this.setSize(585,650);
        
        iniciarMundo();
       
        
        
//        Circulo laserCohete = new Circulo(Color.ORANGE, Color.YELLOW, false, false, true, this.player.getX()+22, this.player.getY(), 5);
//        this.lienzo1.getFiguras().add(laserCohete);
        
//        for (int i = 0; i < 10; i++) {
//            int random = (int) Math.ceil(Math.random()*25);
//            System.out.println(random);
//        }
        
//        for (int i = 0; i < 10; i++) {
//            int random = ThreadLocalRandom.current().nextInt(0, 10);
//            System.out.println(random);
//        }
        
        
    }
    public void iniciarMundo(){
        this.player=new Imagen(false, false, false, 200, 500, "src/Imagenes/transbordador-espacial.png", 50, 70);
        this.lienzo1.getFiguras().add(this.player);
        
        Imagen asteroide_1 =new Imagen(true, false, true, 200, 0, "src/Imagenes/asteroide.png", 80, 60);
        this.lienzo1.getFiguras().add(asteroide_1);
        
        Imagen asteroide_2 =new Imagen(true, false, true, 300, 0, "src/Imagenes/asteroide (1).png", 90, 90);
        this.lienzo1.getFiguras().add(asteroide_2);
        
        Imagen asteroide_3 =new Imagen(true, false, true, 250, 0, "src/Imagenes/asteroide (2).png", 80, 90);
        this.lienzo1.getFiguras().add(asteroide_3);
        
        Imagen asteroide_4 =new Imagen(true, false, true, 100, 0, "src/Imagenes/asteroide (3).png", 80, 80);
        this.lienzo1.getFiguras().add(asteroide_4);
        
        Imagen meteorito =new Imagen(true, false, true, 400, 0, "src/Imagenes/meteorito.png", 80, 80);
        this.lienzo1.getFiguras().add(meteorito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        renew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        start.setBackground(new java.awt.Color(153, 255, 255));
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/start.png"))); // NOI18N
        start.setMaximumSize(new java.awt.Dimension(577, 521));
        start.setMinimumSize(new java.awt.Dimension(577, 521));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        start.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                startKeyPressed(evt);
            }
        });

        pause.setBackground(new java.awt.Color(255, 102, 204));
        pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pause.png"))); // NOI18N
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        renew.setBackground(new java.awt.Color(204, 0, 204));
        renew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/renew.png"))); // NOI18N
        renew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renewActionPerformed(evt);
            }
        });
        renew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                renewKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renew, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(605, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pause)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(renew)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        
        this.proceso = new Thread(this.lienzo1);
        this.lienzo1.setJugando(true);
        proceso.start();
        //this.start.setEnabled(false);
    }//GEN-LAST:event_startActionPerformed

    private void startKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_startKeyPressed
        // TODO add your handling code here:
        this.setFocusable(true);
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_UP){
            //this.player.setY(this.player.getY()-20);
        }else if(key == KeyEvent.VK_LEFT){
            this.player.setX(this.player.getX()-20);
        }else if(key == KeyEvent.VK_DOWN){
            //this.player.setY(this.player.getY()+20);
        }else if(key == KeyEvent.VK_RIGHT){
            this.player.setX(this.player.getX()+20);
        }else if(key == KeyEvent.VK_SPACE){
            Imagen bala=new Imagen(false, false, false, 300, 500, "src/Imagenes/bullet.png", 50, 70);
            this.lienzo1.getFiguras().add(bala);
        }
        
    }//GEN-LAST:event_startKeyPressed

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        this.lienzo1.setJugando(false);
        this.start.setEnabled(false);
        
    }//GEN-LAST:event_pauseActionPerformed

    private void renewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renewActionPerformed
        // TODO add your handling code here:
        this.proceso = new Thread(this.lienzo1);
        this.lienzo1.setJugando(false);
        this.lienzo1.setFiguras(new LinkedList<>());
        iniciarMundo();
        this.lienzo1.setJugando(true);
        this.proceso.start();
        
    }//GEN-LAST:event_renewActionPerformed

    private void renewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_renewKeyPressed
        // TODO add your handling code here:
        this.setFocusable(true);
        int key = evt.getKeyCode();
        if(key == KeyEvent.VK_UP){
            //this.player.setY(this.player.getY()-20);
        }else if(key == KeyEvent.VK_LEFT){
            this.player.setX(this.player.getX()-20);
        }else if(key == KeyEvent.VK_DOWN){
            //this.player.setY(this.player.getY()+20);
        }else if(key == KeyEvent.VK_RIGHT){
            this.player.setX(this.player.getX()+20);
        }else if(key == KeyEvent.VK_SPACE){
            Imagen bala=new Imagen(false, false, false, 300, 500, "src/Imagenes/bullet.png", 50, 70);
            this.lienzo1.getFiguras().add(bala);
        }
    }//GEN-LAST:event_renewKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pause;
    private javax.swing.JButton renew;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
